# Generated by Django 4.1 on 2024-05-04 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("title", models.TextField(null=True)),
                ("image_url", models.URLField(max_length=1000, null=True)),
                (
                    "image_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1000, null=True), null=True, size=None
                    ),
                ),
                ("cms_product_id", models.CharField(max_length=20, unique=True)),
                ("cms_product_handle", models.TextField(null=True)),
                (
                    "variant_options",
                    django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None),
                ),
                ("description", models.TextField(null=True)),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("shop_url", models.URLField(unique=True)),
                ("access_token", models.CharField(max_length=80)),
                ("test", models.BooleanField(default=False)),
                ("logo_uploaded", models.BooleanField(default=False)),
                ("logo_extension", models.CharField(max_length=8, null=True)),
                (
                    "cms",
                    models.CharField(
                        choices=[("Shopfiy", "Shopify"), ("Presta", "Presta")], default="Shopfiy", max_length=16
                    ),
                ),
            ],
            options={
                "db_table": "shops",
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("shop_url", models.URLField()),
                ("image_url", models.URLField(max_length=1000, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("title", models.TextField(null=True)),
                (
                    "options",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1000, null=True), size=None
                    ),
                ),
                ("inventory_quantity", models.IntegerField(default=0)),
                ("cms_variant_id", models.CharField(max_length=20)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="home.product"
                    ),
                ),
            ],
            options={
                "db_table": "variants",
            },
        ),
        migrations.CreateModel(
            name="UpsellWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("offer_name", models.CharField(blank=True, max_length=256)),
                ("offer_description", models.TextField(blank=True)),
                ("upsell_product_id", models.CharField(max_length=64)),
                (
                    "trigger_product_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64), blank=True, default=list, null=True, size=None
                    ),
                ),
                ("discount_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="upsell_widgets", to="home.shop"
                    ),
                ),
            ],
            options={
                "db_table": "upsell_widgets",
            },
        ),
        migrations.CreateModel(
            name="UpsellImpression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("order_id", models.BigIntegerField(null=True)),
                ("checkout_token", models.CharField(max_length=256, null=True)),
                ("customer_id", models.BigIntegerField(null=True)),
                ("customer_email", models.EmailField(max_length=254, null=True)),
                ("customer_first_name", models.CharField(max_length=128, null=True)),
                ("customer_last_name", models.CharField(max_length=128, null=True)),
                ("page_url", models.URLField(max_length=1024, null=True)),
                (
                    "upsell_widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_impressions",
                        to="home.upsellwidget",
                    ),
                ),
            ],
            options={
                "db_table": "upsell_impressions",
                "unique_together": {("upsell_widget", "checkout_token")},
            },
        ),
        migrations.CreateModel(
            name="UpsellConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "upsell_impression",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_conversion",
                        to="home.upsellimpression",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upsell_conversions",
                        to="home.variant",
                    ),
                ),
            ],
            options={
                "db_table": "upsell_conversions",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="products", to="home.shop"
            ),
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("code", models.CharField(max_length=20, null=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "value_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")], max_length=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("deleted", "Deleted"),
                            ("expired", "Expired"),
                            ("scheduled", "Scheduled"),
                        ],
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("cms_discount_id", models.CharField(max_length=64, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discounts", to="home.shop"
                    ),
                ),
            ],
            options={
                "db_table": "discounts",
            },
        ),
        migrations.CreateModel(
            name="CrossSellWidget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive"), ("deleted", "Deleted")],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "cms_product_ids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_sell_widgets",
                        to="home.discount",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cross_sell_widgets", to="home.shop"
                    ),
                ),
            ],
            options={
                "db_table": "cross_sell_widgets",
            },
        ),
        migrations.CreateModel(
            name="CrossSellImpression",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("order_id", models.BigIntegerField(null=True)),
                ("checkout_token", models.CharField(max_length=256, null=True)),
                ("customer_id", models.BigIntegerField(null=True)),
                ("customer_email", models.EmailField(max_length=254, null=True)),
                ("customer_first_name", models.CharField(max_length=128, null=True)),
                ("customer_last_name", models.CharField(max_length=128, null=True)),
                ("page_url", models.URLField(max_length=1024, null=True)),
                ("purchase_shop_url", models.URLField()),
                (
                    "recommended_shop_urls",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(max_length=1000), blank=True, default=list, size=None
                    ),
                ),
                (
                    "cross_sell_widgets",
                    models.ManyToManyField(related_name="cross_sell_impressions", to="home.crosssellwidget"),
                ),
            ],
            options={
                "db_table": "cross_sell_impressions",
                "unique_together": {("purchase_shop_url", "checkout_token")},
            },
        ),
        migrations.CreateModel(
            name="CrossSellClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("purchase_shop_url", models.URLField(null=True)),
                ("rdir", models.URLField(max_length=500, null=True)),
                ("checkout_page_url", models.URLField(max_length=1024, null=True)),
                (
                    "impression",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="home.crosssellimpression",
                    ),
                ),
            ],
            options={
                "db_table": "cross_sell_clicks",
                "unique_together": {("purchase_shop_url", "impression", "rdir")},
            },
        ),
        migrations.CreateModel(
            name="CrossSellConversion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("purchase_shop_url", models.URLField()),
                ("checkout_token", models.CharField(max_length=256, null=True)),
                ("customer_id", models.BigIntegerField(null=True)),
                ("customer_email", models.EmailField(max_length=254, null=True)),
                ("customer_first_name", models.CharField(max_length=128, null=True)),
                ("customer_last_name", models.CharField(max_length=128, null=True)),
                (
                    "cms_variant_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), default=list, size=None
                    ),
                ),
                (
                    "quantities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                ("sales", models.FloatField()),
                ("clicks", models.ManyToManyField(related_name="cross_sell_conversions", to="home.crosssellclick")),
                (
                    "impressions",
                    models.ManyToManyField(related_name="cross_sell_conversions", to="home.crosssellimpression"),
                ),
            ],
            options={
                "db_table": "cross_sell_conversions",
                "unique_together": {("purchase_shop_url", "checkout_token")},
            },
        ),
    ]
