# Generated by Django 4.1 on 2026-01-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopifyWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("webhook_id", models.CharField(max_length=255, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
