#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Running collectstatic..."
python crosslink/manage.py collectstatic --noinput

echo "Runing migrate..."
python crosslink/manage.py makemigrations
python crosslink/manage.py migrate

echo "Running runserver..."
PYTHONUNBUFFERED=1 python crosslink/manage.py runsslserver 0.0.0.0:8000 --certificate cert.pem --key key.pem

